version: '3'

services:
    redis:
        image: ${REDIS_IMAGE}
        container_name: ${REDIS_CONTAINER_NAME:-redis}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ./redis/redis.conf:/etc/redis/redis.conf
            - ./redis/data:/data
        ports:
            - ${REDIS_PORT}:6379
